# Site settings
title: UXRIM
header-img: img/home-bg.jpg
email: kamlekar.venkatesh@gmail.com
description: "This is Venkateshwar's blog where I share my experiences in web development as well as thoughts which I want to say to others."
baseurl: ""
url: "http://uxrim.com"
twitter_username: feedmeaddiction
github_username:  kamlekar
facebook_username:  
disqus_shortname: uxrim
google_analytics: true

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
